### ISSUE TITLE
Feature request: "changed" event on form

### ISSUE THREAD

**Issue by emanuele-falzone** [B3rn475/IFMLEdit.org#14]
It would be useful to have a "changed" event on each form that captures changes in the value of the fields.

**Comment by B3rn475** [comment]
Possible use-case

![changed](https://user-images.githubusercontent.com/2686902/36354712-ca981b50-14d8-11e8-95e0-90f58ef48f9d.png)

**Comment by B3rn475** [comment]
System events enable this feature in a generic way.
