### ISSUE TITLE
Feature request: "back" event on ViewContainer

### ISSUE THREAD

**Issue by emanuele-falzone** [B3rn475/IFMLEdit.org#15]
It would be useful to have a "back" event on a ViewContainer. The event should be mapped to the back button. When the back button is pressed the "back" event should be triggered. It could be platform depended (what about iOS?).

**Comment by B3rn475** [comment]
The introduction of system events could solve the problem without the need to introduce details

Related https://github.com/B3rn475/IFMLEdit.org/pull/19

**Comment by B3rn475** [comment]
System events enable this feature in a generic way.
