### ISSUE TITLE
ID field - Abnormal behavior

### ISSUE THREAD

**Issue by molinellidavide** [B3rn475/IFMLEdit.org#20]
When you generate a model, if you delete the id of a component and close the panel, and then you move to another component, then the component whose id is deleted is no longer clickable or editable. If afterwards you delete the id of another component, the second time the framework regenerates a correct id and manages the cancellation of the ID (the component is still clickable and modifiable).

[id_bug.zip](https://github.com/B3rn475/IFMLEdit.org/files/1859368/id_bug.zip)

**Comment by B3rn475** [comment]
Fixed in **almost-joint**
Related https://github.com/B3rn475/almostjs-joint/commit/bd4f685434274104b5d998ea25964a6c5bd9e804

**Comment by molinellidavide** [comment]
Problem correctly solved.
