### ISSUE TITLE
Event navigation-flow - strange behavior

### ISSUE THREAD

**Issue by molinellidavide** [B3rn475/IFMLEdit.org#22]
In an attempt to drag a navigation flow, detaching it from an event and leaving it "dangling", the behavior is not possible (correct).
But if you execute ctrl + z twice (or cmd + z for mac) you get that the navigation-flow remains "dangling" (unforeseen behavior).

[cmd+z.zip](https://github.com/B3rn475/IFMLEdit.org/files/1861469/cmd.z.zip)

**Comment by B3rn475** [comment]
Confirmed even for DataFlows

**Comment by B3rn475** [comment]
It has been fixed in almost-joint

Related https://github.com/B3rn475/almostjs-joint/commit/0273779446884e8505f3146cb10b187f3aea1475

**Comment by molinellidavide** [comment]
Problem correctly fixed.
