### ISSUE TITLE
Strange behavior in inserting new element on the board

### ISSUE THREAD

**Issue by molinellidavide** [B3rn475/IFMLEdit.org#30]
When you drag and drop a new element from the sidebar towards the board, if you click and release the element without any movement outside the sidebar and then you re-click the same element and execute the drag and drop outside the sidebar, the element does not follow the mouse pointer, but is "hanging" in an apparently non-deterministic position of the board.

N.B.: the zip file in attachment contains a video demo to help in understing the problem. I hope you find it useful.
[bug.zip](https://github.com/B3rn475/IFMLEdit.org/files/2453970/bug.zip)

**Comment by B3rn475** [comment]
Fixed in https://github.com/B3rn475/almostjs-joint/issues/10

**Comment by B3rn475** [comment]
@molinellidavide can you double check?

**Comment by molinellidavide** [comment]
I confirm that the problem has been correctly solved. Thank you!
