### ISSUE TITLE
Out of date navigation flow filter data binding

### ISSUE THREAD

**Issue by molinellidavide** [B3rn475/IFMLEdit.org#31]
Consider the following modeling context: you have an event attached to a form ViewComponent with a navigation flow pointing towards a list ViewComponent.
If you establish a binding between a form parameter and a filter parameter of the list and then you delete the filter parameter of the list, the binding continue to be present even if the parameter does not exist anymore.

In attachment, a video demo of the possible unexpected behavior.

[bug-filter.zip](https://github.com/B3rn475/IFMLEdit.org/files/2461266/bug-filter.zip)

**Comment by B3rn475** [comment]
Flows should listen for these events and update accordingly

**Comment by B3rn475** [comment]
@molinellidavide can you double check?

**Comment by molinellidavide** [comment]
It seems that the problem has not been completely solved. Take a look at this demo video:

[demo.zip](https://github.com/B3rn475/IFMLEdit.org/files/2896557/demo.zip)

**Comment by B3rn475** [comment]
I do confirm that the problem persists.

It is related to the `ModelEdit` reusing the array object in the `StringsSet` instead on slicing it as in the `Bindings` and `ElementsList`

**Comment by B3rn475** [comment]
@molinellidavide can you double check?

**Comment by molinellidavide** [comment]
I confirm the problem has been completely solved. Thank You!
