### ISSUE TITLE
Gulp fails when trying to compile application on nodejs 12 lts or higher

### ISSUE THREAD

**Issue by AlexandroDRK** [B3rn475/IFMLEdit.org#35]
I tried to run the application for a research project that aims to generate automatic test scripts using the cypress tool, and when running the command "npm install" the dependencies are installed but gulp fails to compile the application. I'm using ubuntu linux 22.10 and I tried to run using the current LTS nodejs (18.x.x), I tried to update the dependencies to newer versions and even tried to install the 2020 LTS nodejs and still the failures persist. If possible @B3rn475 , could you try to update the project's dependencies to help me with this problem, thanks in advance.

**Comment by B3rn475** [comment]
It should be fixed now.

Feel free to reopen this issue if it is not.

**Comment by AlexandroDRK** [comment]
Thank you, this update allowed me to generate the application's assets perfectly, at first I had problems with the newer version of openssl, however this problem was quickly overcome.

**Comment by AlexandroDRK** [comment]
> It should be fixed now.
> 
> Feel free to reopen this issue if it is not.

Thank you, this update allowed me to generate the application's assets perfectly, at first I had problems with the newer version of openssl, however this problem was quickly overcome.
